In [7]:
# IMPORTAÇÃO DAS BIBLIOTECAS
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import datasets
from keras.models import Sequential
from keras.layers import Dense 
from keras.utils import to_categorical
from keras.utils import to_categorical

In [2]:
# Carregamento ba bae de dados e criação dos previsores (variaveis indepedentes - X) e da classe (variavel dependente - y)
base = datasets.load_iris()
previsores = base.data 
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# Transformação da classe para o formato "dummy", pois temos uma rede neural com 3 neuronios na camada de saida
classe_dummy = to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [11]:
# Divisao da base de dados entre treinamento e teste (30% para testar e 70% para treinar)
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores, 
                                                                  classe_dummy,
                                                                  test_size=0.3,
                                                                  random_state=0)

In [12]:
# Criação da estrutura de rede neural cm a classe sequential (sequencia de camadas)
modelo = Sequential()
# Primeira camada oculta, 5 neuronios, 4 neuronios de entrada 
modelo.add(Dense(units = 5, input_dim = 4))
#Segunda camarada oculta
modelo.add(Dense(units=4))
# Terceira camada oculta 
# Função softmax porque temos um problema de classificação com mais de dua classes
# (é gerada uma probabilidade em cada neuronio)
modelo.add(Dense(units=3, activation='softmax'))


In [13]:
# Visualização da estrutura da rede neural
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 25        
                                                                 
 dense_1 (Dense)             (None, 4)                 24        
                                                                 
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
Total params: 64 (256.00 Byte)
Trainable params: 64 (256.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
# Configuração dos parametros da rede neural (adam = algoritmo para atualizar os peses e loss = calculo do erro)
modelo.compile(optimizer= 'adam', loss = 'categorical_crossentropy',
               metrics=['accuracy'])
# Treinamento, dividindo a base de treinamento em uma porção para validação (validation_data)
modelo.fit(X_treinamento, y_treinamento, epochs= 1000,
           validation_data= (X_teste, y_teste))


Epoch 1/1000
4/4 [==============================] - 3s 253ms/step - loss: 6.3678 - accuracy: 0.3048 - val_loss: 5.1483 - val_accuracy: 0.4000
Epoch 2/1000
4/4 [==============================] - 0s 44ms/step - loss: 5.9488 - accuracy: 0.3048 - val_loss: 4.7993 - val_accuracy: 0.4000
Epoch 3/1000
4/4 [==============================] - 0s 43ms/step - loss: 5.5347 - accuracy: 0.3048 - val_loss: 4.4561 - val_accuracy: 0.4000
Epoch 4/1000
4/4 [==============================] - 0s 43ms/step - loss: 5.1487 - accuracy: 0.3048 - val_loss: 4.1223 - val_accuracy: 0.4000
Epoch 5/1000
4/4 [==============================] - 0s 43ms/step - loss: 4.7560 - accuracy: 0.3048 - val_loss: 3.7975 - val_accuracy: 0.4000
Epoch 6/1000
4/4 [==============================] - 0s 43ms/step - loss: 4.3723 - accuracy: 0.3048 - val_loss: 3.4802 - val_accuracy: 0.4000
Epoch 7/1000
4/4 [==============================] - 0s 47ms/step - loss: 4.0170 - accuracy: 0.3048 - val_loss: 3.1695 - val_accuracy: 0.4000
Epoch 8/1000

In [16]:
# Previsoes e mudar a variavel par True ou False de acordo cm o thereshold 0.5
previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

2/2 [==============================] - 0s 7ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [17]:
# Como é um problrma com 3 saidas, precisamos buscar a posição que possui o maior valor (sao retornados 3 valores)
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

In [18]:
# Geração da matriz de confusao
confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)